apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_THREADS_VIRTUAL_ENABLED
              value: "true"
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084




