apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_MAIL_HOST
              value: "sandbox.smtp.mailtrap.io"
            - name: SPRING_MAIL_PORT
              value: "2525"
            - name: SPRING_MAIL_USERNAME
              value: "TU_USERNAME_MAILTRAP"
            - name: SPRING_MAIL_PASSWORD
              value: "TU_PASSWORD_MAILTRAP"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084