apiVersion: v1
kind: Secret
metadata:
  name: databases-secret
type: Opaque
stringData:
  mongo-root-password: "password"
  mysql-root-password: "root"
  postgres-order-password: "admin"
  postgres-keycloak-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  admin-password: "YOUR_PROD_GRAFANA_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  admin-username: "YOUR_PROD_KEYCLOAK_USERNAME"
  admin-password: "YOUR_PROD_KEYCLOAK_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
stringData:
  username: "YOUR_PROD_EMAIL@gmail.com"
  password: "YOUR_PROD_APP_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: mercadopago-secret
type: Opaque
stringData:
  access-token: "TEST-3297189159340717-092318-753e7cfa2e098a50a2721588e1f3144e-161033155"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secrets
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "YOUR_PROD_CLOUD_NAME"
  CLOUDINARY_API_KEY: "YOUR_PROD_API_KEY"
  CLOUDINARY_API_SECRET: "YOUR_PROD_API_SECRET"

---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
type: Opaque
stringData:
  oauth2-client-secret: "T97taw6Bspm2OYT6ImLVnusa5mG5m2SJ"





