server:
  port: 8085
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  config:
    import: "" # Overrides application.yaml to prevent config server connection timeout
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN:TEST-dummy-token}
  mock:
    enabled: ${MERCADOPAGO_MOCK_ENABLED:false}

eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
