server:
  port: 8085
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://localhost:8888"

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN:TEST-dummy-token}
  mock:
    enabled: ${MERCADOPAGO_MOCK_ENABLED:false}

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
